language: php
php:
#  - 5.3.3
  - 5.3
#  - 5.4
env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=dev-master
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --no-interaction require --dev symfony/twig-bundle:${SYMFONY_VERSION} symfony/symfony:${SYMFONY_VERSION}
notifications:
  email:
    - christian.raue@gmail.com
