language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
env:
  - SYMFONY_VERSION=origin/2.0
  - SYMFONY_VERSION=origin/master
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
notifications:
  email:
    - christian.raue@gmail.com
