language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.7.*" PHPUNIT_BRIDGE=true

matrix:
  include:
    - php: 5.3.3
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.4.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.5.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.6.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.8.*" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
    - php: 5.5
      env: SYMFONY_VERSION="dev-master" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
  allow_failures:
    - php: 7.0
    - php: hhvm
    - env: SYMFONY_VERSION="2.8.*" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
    - env: SYMFONY_VERSION="dev-master" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"

install:
  - if [ "${TRAVIS_PHP_VERSION}" != "7.0" ] && [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
  - sh travis_install_dependencies.sh

notifications:
  email:
    on_success: always
    on_failure: always

# use container-based infrastructure
sudo: false

# cache Composer's package cache
cache:
  directories:
    - $HOME/.composer/cache/files
