language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
env:
  - SYMFONY_VERSION="2.0.*" MIN_STABILITY="stable"
  - SYMFONY_VERSION="2.1.*" MIN_STABILITY="stable"
  - SYMFONY_VERSION="2.2.*" MIN_STABILITY="dev"
before_script:
  - sh travis_before_build.sh
notifications:
  email:
    - christian.raue@gmail.com
