language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION='2.7.*' TWIG_VERSION='~1.0'

matrix:
  include:
    - php: hhvm
      dist: trusty
    - php: 5.3
      env: DEPS='lowest'
    - php: 5.6
      env: DEPS='unmodified'
    - php: 7.1
      env: DEPS='unmodified'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*' TWIG_VERSION='~1.0'
    - php: 5.6
      env: SYMFONY_VERSION='3.2.*' TWIG_VERSION='~1.0'
    - php: 5.6
      env: SYMFONY_VERSION='3.3.*' TWIG_VERSION='~1.0'
    - php: 7.1
      env: SYMFONY_VERSION='3.4.*' TWIG_VERSION='~2.0' MIN_STABILITY='dev'
  allow_failures:
    - env: SYMFONY_VERSION='3.4.*' TWIG_VERSION='~2.0' MIN_STABILITY='dev'
  fast_finish: true

install:
  # disable Xdebug for better Composer performance
  - if [ "${TRAVIS_PHP_VERSION}" != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi;
  # set unlimited memory_limit
  - if [ "${TRAVIS_PHP_VERSION}" != 'hhvm' ]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi;
  - echo "memory_limit = -1" >> "${INI_FILE}"
  # install dependencies using Composer
  - bash .travis_install_dependencies.sh
  # show installed dependencies
  - composer show

script:
  # validate composer.json
  - composer validate --strict --no-check-lock
  # run PHPUnit
  - vendor/bin/phpunit -v

notifications:
  email:
    on_success: always
    on_failure: always

# use container-based infrastructure
sudo: false

# cache Composer's package cache
cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
