language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=dev-master
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --no-interaction --no-update require symfony/symfony:${SYMFONY_VERSION} symfony/twig-bundle:${SYMFONY_VERSION}
  - php composer.phar --no-interaction --no-update require --dev symfony/symfony:${SYMFONY_VERSION}
  - php composer.phar --no-interaction update --dev
notifications:
  email:
    - christian.raue@gmail.com
